- templates/matplotlibrc
This PR increases the contrast in the default matplotlibrc used in tutorials, and switches back to a more modern-looking font (resolves #66). Of course such things are subjective, but I feel strongly that the current style emphasizes aesthetics (nice, soft-looking) over legibility, particularly for anyone with less-than-perfect vision.
Old style
New style
> Increase contrast and switch default font for tutorials

- tutorials/FITS-tables/FITS-tables.ipynb
While showing some of the tutorials to some people, I noticed in the FITS-tables tutorial that there's a use of `np.where` that's unnecessary.  That is, a boolean mask will work just fine.
I find this is a common mistake people make transitioning from IDL, so I think it's much better if we avoid using ``np.where`` wherever possible.  So this change just removes the ``np.where`` call.
Is that ok with you @adrn and @eblur (I think you wrote this originally, right @eblur)?
> remove unneeded np.where in FITS-tables

- tutorials/FITS-header/FITS-header.ipynb
- tutorials/FITS-images/FITS-images.ipynb
- tutorials/FITS-tables/FITS-tables.ipynb
- tutorials/Plot-Catalog/plot-catalog.ipynb
- tutorials/Quantities/Quantities.ipynb
Recently I've had the opportunity to teach a few classes/workshops around Astropy, and the tutorials have been great for this purpose.  
However, most are lacking in one important aspect as active learning tools: they are tutorials that lack prompts for the person taking the tutorial to interact!  The exception is the UVES tutorial, which @hamogu and @migueldvb put a lot of work into to include "exercises".  Taking a page from that tutorial, this PR adds exercises to all of the other tutorials.
I hate to be a pain about this, but I think this should probably be merged before other PRs that might conflict, because this touches a lot of stuff so merging might be quite a bit more problematic for this one...
cc @adrn @kelle  @astrofrog
> Add questions/exercises to tutorials

- deploy
This updates the ``deploy`` script basically just to make it easier when the remote for astropy isn't called "origin" - it now prompts for a name if "origin" isn't avaialble. (I use "astropy" as the remote so I don't get confused between the "eteq" and "astropy" github accounts...)
cc @adrn as I think the main author of the script
> Update the deploy script to make it easier with non "origin" remote

- .travis.yml
- .travis/setup_dependencies.sh
- .travis/setup_environment.sh
This adds the necessary travis config files to have travis check that the notebooks actually run properly using `python prepare_deploy.py run`.
@eteq does this look right?
> Add travis build to check that notebooks run

- tutorials/UVES/UVES.ipynb
Two things to note:
- I did not review the full notebook. I just looked over it and fixed a couple of simple typos in the text or code.
- I'm running a newer version of IPython, so unfortunately this upgraded to notebook version 4 when I saved it, thus my edits might be hard to find between the lines that are just format changed, but I promise it's only better (word order, some comment lines had wrong indentation in code, one variable was missspelled causing a "show full traceback" button, markdown rendered a "*" as italics instead of "multiply").
Before merging please make sure the IPython that renders the production version (I have no idea how you set that up) works with this version.
> fix some simple typos in UVES tutorial

- .travis.yml
- .travis/setup_environment.sh
In case there'll be tutorial hacking at #dotastro, travis should be able to be run.
Also opted in the container based travis from the legacy.
> Updating .travis to reflect recent miniconda path changes

- .travis.yml
- deploy
- travis_deploy
This should close #93 by finally setting it up so that merging a PR into master auto-deploys to github pages.  
The main idea is that this modifys the ``deploy`` script to allow non-interactive use, as well as the @astropy-bot account as a user that has the appropriate access privileges along with a travis-encrypted access token. 
The awkward thing is that we can't test it really until merging, as it's specifically *not* supposed to work until merged into master.  If it helps any, though, you can see the results of this by looking at https://github.com/eteq/astropy-tutorials/tree/gh-pages, which was made by the build you see at https://travis-ci.org/eteq/astropy-tutorials/builds/94067132 .  This should be basically the same, except with new tokens and such as relevant for the real …
> Auto deploy machinery

- README.md
The links to binder have changed and this PR updates to the current URLs.
> Update to the current version of binder

- tutorials/notebooks/coordinates/coordinates.ipynb
There was some raw HTML in a markdown cell that doesn't get rendered properly when converted to RST. I just make the footnote text italic instead.
I intended to also fix the links (i.e. #180) but can't figure out a good solution. See discussion in the issue.
> Remove footnote from coordinates tutorial

- tutorials/_static/custom.css
- tutorials/astropy.tpl
This closes #188 by making a surprisingly simple change to the templates.
This isn't *quite* what I think we wanted, because the In/Out text is *above* the cell instead of to the left of it like a notebook.  But I think it's close enough because it makes the distinction much clearer.
Here's what things end up looking like after this PR:
> Add In/Out markers to generated cells

- tutorials/notebooks/vo/conesearch.ipynb
Fix Vizier URLs, à la https://github.com/astropy/astroquery/pull/1102/files
> Fix conesearch tutorial

- .circleci/config.yml
- .circleci/rtd-push.sh
- pip-requirements.txt
- scripts/convert.py
After a conversation with @cadair, he convinced me that we might be able to solve our build issues by running the tutorial build on CircleCI and then pushing the documentation from there to either readthedocs or github pages. The advantage of building on a CI service is that we can cache data files, which is what causes our timeouts and headaches on RTD right now. This is a PR to test out the CircleCI build - *do not merge* yet!
> Try circleci

- tutorials/notebooks/FITS-header/FITS-header.ipynb
Since this is the FITS header editing section, and a commonly-needed thing is just updating FITS header kws (e.g., when you are given data with bad WCS keywords...), inplace updating seems important to show
> Add an example of inplace updating to tutorial

- tutorials/notebooks/synthetic-images/synthetic-images.ipynb
*This should only get merged once astropy/astropy-data#48 is merged!*
This updates the new tutorials to download data files from the data.astropy.org repo. Those files are significantly smaller than the originals: I cut out sections of the images to make the files smaller and make the downloads more manageable. They still require downloading >100MB of data...
> Update tutorials to use new image files

- tutorials/conf.py
- tutorials/dev.rst
This adds a bit to the ``conf.py`` to grab an environment variable to use for determining which kernel runs the notebooks.  Also adds a bit to the dev docs to explain this.
I'm not super happy using an environment variable for this, but I couldn't come up with any other way that works with ``make html``.  Open to ideas but if no one else has something this is better than nothing.
cc @MananAgarwal @adrn
> Allow kernel setting from environment variable

- .rtd-environment.yml
- environment.yml
- pip-requirements.txt
- tutorials/notebooks/FITS-cubes/requirements.txt
We started to see old issues (https://travis-ci.org/astropy/astropy-tutorials/builds/390649359#L871) that has been solved for a while upstream in astroquery (https://github.com/astropy/astroquery/issues/1021).
It's not perfectly clear why the notebook started to run into it again, I suspect there may be some issues with the versions installed (#234), but as the first measure we should let the installer to pick up more recent astroqueries (given it's not like other packages, if an old version used to work, it's not guaranteed at all it still works due to its dependency on upstream services that can change beyond our control).
> Astroquery should be strictly pinned

- scripts/convert.py
To work with a newer version of jupyter_client released within the last week or so, I had to remove the default kernel name ExecutePreprocessor.kernel_name.default_value added by @eteq.
> Only pass kernel name if passed in

- tutorials/conf.py
- tutorials/dev.rst
In the spirit of the new `NBCONVERT_KERNEL` environment variable, this PR adds a check for the `NBFILE` environment variable, which allows specifying the path to a single notebook file to execute and build. This is very useful for testing the end-to-end build process on a single tutorial first, before running on all tutorials (which takes quite a bit of time!).
(Also, to work with a newer version of `jupyter_client` released within the last week or so, I had to remove the default kernel name `ExecutePreprocessor.kernel_name.default_value` added by @eteq)
> Add option to run one notebook file

- .circleci/config.yml
- scripts/convert.py
- tutorials/notebooks/Coordinates-Intro/Coordinates-Intro.ipynb
- tutorials/notebooks/Coordinates-Transform/Coordinates-Transform.ipynb
- tutorials/notebooks/FITS-cubes/FITS-cubes.ipynb
- tutorials/notebooks/FITS-header/FITS-header.ipynb
- tutorials/notebooks/FITS-images/FITS-images.ipynb
- tutorials/notebooks/FITS-tables/FITS-tables.ipynb
- tutorials/notebooks/Models-Quick-Fit/Models-Quick-Fit.ipynb
- tutorials/notebooks/UVES/UVES.ipynb
- tutorials/notebooks/plot-catalog/plot-catalog.ipynb
- tutorials/notebooks/quantities/quantities.ipynb
- tutorials/notebooks/redshift-plot/redshift-plot.ipynb
- tutorials/notebooks/synthetic-images/synthetic-images.ipynb
- tutorials/notebooks/units-and-integration/units-and-integration.ipynb
- tutorials/notebooks/vo/conesearch.ipynb
This is a first stab at making the tutorial headers (i.e. the first markdown cell in each notebook) more uniform across the tutorials. We need this for #247 so that each notebook specifies a set of keywords. I tried to add summaries where notebooks didn't have them, but many are missing learning goals. 
Could the authors please provide a set of learning goals (bulleted list of a few key takeaways) for:
* Viewing and manipulating FITS images (author @eblur)
* Viewing and manipulating FITS tables (author @eblur)
* Using Astropy Quantities for astrophysical calculations (authors Ana Bonaca, @eteq)
* Make a plot with both redshift and universe age axes using astropy.cosmology (author Neil Crighton)
* Analyzing UVES Spectroscopy with Astropy (@hamogu @migueldvb)
* VO Simple Cone Search …
> Make tutorial headers more uniform

- tutorials/notebooks/Coordinates-Transform/Coordinates-Transform.ipynb
The ### section "Introducting frame transformations" to "Introducing frame transformations"
> Fixed a ### typo

- tutorials/notebooks/UVES/UVES.ipynb
Backticks in markdown links cause issues when converted to RST.
> Remove backticks from links in UVES tutorial

- tutorials/themes/tutorials-theme/layout.html
I have fixed the sidebar on the tutorials home page to the top, but I have allowed the sidebar (containing the table of contents) on individual tutorial pages to stick on the screen on scrolling. This will allow the viewer to easily navigate across the tutorial. To avoid the scrolling issue in these pages, I fix the sidebar whenever the size of the browser window is reduced beyond a limit.
> Fixed the scrolling issue on tutorials home page

- CONTRIBUTING.rst
Fixes #284 
Links jupyter notebook style guides([STScI style guide](https://github.com/spacetelescope/style-guides/blob/master/guides/jupyter-notebooks.md) and [Official coding style](https://jupyter.readthedocs.io/en/latest/development_guide/coding_style.html)) to Contributing.rst
> Link jupyter notebook style guides to Contributing.rst

- quarantine/FITS-cubes/FITS-cubes.ipynb
- tutorials/notebooks/quantities/quantities.ipynb
To follow up on Issue #289. 
Two goals in mind:
1. Update code blocks to replace outdated code snippets
2. Reduce cube file size to manageable level
> Updating FITS-cubes tutorial in quarantine

- tutorials/themes/tutorials-theme/navbar.html
Fixes #307 
Clicking on the Learn Astropy banner now redirects to [homepage](http://www.astropy.org/astropy-tutorials).
> Redirect learn.astropy banner to homepage

- tutorials/notebooks/quantities/quantities.ipynb
To follow up on Issue #322. Adding the keyword "data cubes" to the Quantities tutorial as some part of the tutorial clearly deals with some data cube setup procedure with NumPy (as in "2. Molecular cloud mass").  
Noticed also that the "Learning Goals" have been listed as "TODO", will follow this up with another PR to add the relevant learning goals.
> To add "data cubes" keyword to Quantities tutorial 

- tutorials/conf.py
- tutorials/themes/tutorials-theme/layout.html
- tutorials/themes/tutorials-theme/navbar.html
- tutorials/themes/tutorials-theme/theme.conf
Fixes #323. 
Attempts to mend broken Astropy logo banner link on the tutorial pages, in order for the image on the left hand side of the Learn Astropy navbar to show properly.
> Debug navbar code to fix logo broken link

- tutorials/themes/tutorials-theme/static/searchtools.js
- tutorials/themes/tutorials-theme/tutorialfilters.html
To follow up on PR #340. To try and find a way to add back filter search warning when no tutorials are returned on a filter search. 
Fixes #337.
> Try and add filter search warning when no results is returned

- environment.yml
- pip-requirements.txt
- tutorials/notebooks/quantities/requirements.txt
I verified that Quantities notebook `plt.hist(v)` command worked in matplotlib version 3.0.2 and forced that to be the requirement for now.
Will open an Issue with astropy quantities people so that it works in matplotlib version 3.1 (the latest).
> Add matplotlib version requirement to Quantities

- .gitignore
The gitignore file was ignoring *.fits but not *.fits.gz, so the files were getting `git add`'ed into the push. This should fix it!
This fixes #361
> Ignore fits and gz files in gitignore

- tutorials/themes/tutorials-theme/layout.html
- tutorials/themes/tutorials-theme/navbar.html
- tutorials/themes/tutorials-theme/static/searchtools.js
This PR is my attempt to fix #304.
This adjusts the way the search query is handled in javascript and assumes that no query string means filterTutorials.
> Hide filterTutorials from URL

- tutorials/notebooks/quantities/quantities.ipynb
Using the function `astropy.visualization.quantities_support` makes the plotting tasks in this notebook more resilient to changes among matplotlib versions.
See https://github.com/astropy/astropy/issues/8743
> Add astropy.visualization.quantities_support

- tutorials/notebooks/quantities/quantities.ipynb
Fixes #375. 
To change the title of the Quantities to include the term "Units" to better adhere to convention used in Astropy, as at [https://docs.astropy.org/en/stable/units/](https://docs.astropy.org/en/stable/units/).
> Change Quantities tutorial title to incorporate the term "Units"

- tutorials/notebooks/FITS-tables/FITS-tables.ipynb
Fixes #368.
To add learning goals to the FITS-tables tutorial currently filled by a "TODO" placeholder.
> Add learning goals to FITS-tables tutorial

- tutorials/notebooks/Coordinates-Intro/Coordinates-Intro.ipynb
- tutorials/notebooks/Coordinates-Transform/Coordinates-Transform.ipynb
The word "exercise" has been spelled wrongly as "excercise" in some instances. This PR fixes it.
> Fix spelling of Exercise

- tutorials/dev.rst
I added some text to the developer documentation about how to install `nbstripout`: I think we should all be using this, at least within this repo, to avoid committing notebook output and metadata changes. We should also point contributors to this section if they opt to use the GitHub contribution method.
Tagging everyone so you install it yourself!
@eteq @kelle @eblur @kakirastern @MananAgarwal @lglattly
> Add install instructions for nbstripout

- .circleci/config.yml
We previously installed the dev version, but the circleci build is now failing, possible due to changes in the dev version. I haven't been able to reproduce the failures locally, so this is to try pinning the nbconvert version.
> Pin nbconvert version

- .circleci/config.yml
- environment.yml
- pip-requirements.txt
- Use the pip requirements in the anaconda environment file (to avoid duplication)
- Pinned reproject because with astropy 4.0.1 and reproject 0.6, we are unable to import reproject:
```
KeyErrorTraceback (most recent call last)
<ipython-input-1-5087be31c7cf> in <module>
15 from astroquery.utils import TableList
16 from astropy.wcs import WCS
---> 17 from reproject import reproject_interp
~/project/venv/lib/python3.7/site-packages/reproject/__init__.py in <module>
11 
12 if not _ASTROPY_SETUP_:  # noqa
---> 13     from .interpolation import reproject_interp  # noqa
14     from .spherical_intersect import reproject_exact  # noqa
15     from .healpix import reproject_from_healpix, reproject_to_healpix  # noqa
~/project/venv/lib/python3.7/site-packages/reproject/interpolation/__init__.py in …
```
> Use pip requirements in anaconda environment

- CONTRIBUTING.rst
- pip-requirements.txt
Fixes #454.
Add info to the `CONTRIBUTING.rst` file to add info regarding how to use Zenodo to host large data files plus code snippets that may be needed for this approach to supplement the existing large data file uploading mechanism with http://www.astropy.org/astropy-data/ or http://data.astropy.org.
> Update contributing doc to add uploading data files to Zenodo info

- .github/workflows/build.yml
This PR adds a "repository dispatch" step to the build workflow. What this does is trigger a GitHub Actions run in the astropy/learn-astropy repository. The payload for the trigger includes a reference to the workflow artifact, which will allow the learn-astropy build to download the tutorials artifact.
This requires a GitHub Secret to be set up on the tutorials repo named `DISPATCH_GITHUB_TOKEN` that has write access to the astropy/learn-astropy repository. See https://github.com/peter-evans/repository-dispatch#token
> Add repository-dispatch workflow to deployment

- CNAME
This PR removes the CNAME, as a companion to a PR I'm about to create in astropy/learn-astropy . Together these should have the effect of making learn.astropy.org point to learn-astropy instead of astropy-tutorials.
Note this is ready as-is but should *not* be merged until I've completed the verification process, and then should be merged *before* the follow-on PR (I think...).
cc @adrn @jonathansick @kelle
> Remove CNAME (to move to learn-astropy)

- CONTRIBUTING.rst
There were several links that were broken because line breaks were put in the middle of the URL.
The Jupyter style guidelines link was dead. I put in the first google hit for jupyter style guidelines; I'm not certain it's the appropriate link.
> Fix several broken links

- .github/get_modified_tutorials.py
- .github/workflows/build.yml
- .github/workflows/prs.yml
Refreshing some of the CI config files so that, by default, PR builds only run notebooks that have been modified.
Note: This currently contains a test commit that modifies two notebooks, as a test of the new github actions workflow. That commit should be removed before merging, if this works!
Fixes #519
> Only run modified notebooks in PRs, with an optional label override

- tutorials/spectral-cube-reprojection/SpectralCubeReprojectExample.ipynb
see review on https://github.com/radio-astro-tools/tutorials/pull/17
> Add spectral-cube reprojection tutorial

- tutorials/Models-Quick-Fit/Models-Quick-Fit.ipynb
- [ X] Check the box to confirm that you are familiar with the [contributing guidelines](https://learn.astropy.org/contributing/how-to-contribute) and/or indicate (check the box) that you are familiar with our contributing workflow.
- [X ] Confirm that any contributed tutorials contain a complete Introduction which includes an Author list, Learning Goals, Keywords, Companion Content (if applicable), and a Summary.
- [ X] Check the box to confirm that you are familiar with the Astropy community [code of conduct](https://github.com/astropy/astropy/blob/main/CODE_OF_CONDUCT.md) and you agree to follow the CoC.
I changed all instances of `weights = 1.0/error**2` to `weights = 1.0/error` to address #570.
> fix use of weights in fitting tutorial

- requirements.txt
@adrn 
This PR removes a pin on the `pyvo` dependency.
The dependency is currently pinned to `pyvo==1.2.0`. This is causing several notebook executions to fail because of a call to the deprecated `from astropy.utils.decorators import wraps` from within `pyvo 1.2.0`. From version `1.2.1` onward, `pyvo` instead uses `from functools import partial, wraps` [(pyvo changelog)](https://github.com/astropy/pyvo/blob/89671523011fc6b49f2205ac4a9afd5a43c03025/CHANGES.rst#121-2022-01-12). 
Unpinning `1.2.0` may break something else, but there's no comment in `requirements.txt` as to why it's pinned, so this is a first step to get the notebooks to execute.
> Unpin pyvo dep

- requirements.txt
- tutorials/color-excess/color-excess.ipynb
- tutorials/spectral-cube-reprojection/SpectralCubeReprojectExample.ipynb
- tutorials/vo/conesearch.ipynb
Fixes notebook builds that are failing due to various errors.
> [WIP] Broken notebooks

- .github/workflows/build.yml
- .github/workflows/prs.yml
- .github/workflows/test-scripts.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed

- tutorials/spectral-cube-reprojection/requirements.txt
The `spectral-cube-reprojection` tutorial no longer needs a pin `<2.0` numpy dependency after upstream compatability update in `spectral-cube`.
> Unpin tutorial dependency

- Makefile
- README.md
- binder/requirements.txt
- tutorials/plot-catalog/plot-catalog.ipynb
After removing the global `requirements.txt` in #606, the Binder build broke because it expects that file. In general it expects a single requirements file for all notebooks (see [here](https://stackoverflow.com/questions/59266239/github-binder-requirements-txt); for details of how to specify requirements, see [here](https://mybinder.readthedocs.io/en/latest/using/config_files.html#config-files)).
This PR adds `binder/requirements.txt` to the top-level directory, which Binder uses to successfully build. This single requirements file currently works for all notebooks. If in the future individual notebooks need packages installed with versions that differ from those in `binder/requirements.txt`, execution of those notebooks in Binder will fail.
PR also updates text in the README. 
Closes …
> Binder dependencies

- tutorials/color-excess/color-excess.ipynb
The rendered notebook shows syntax warnings because it can't parse \l which is intended for latex, and shouldn't be interpreted by python
> Escape latex escape sequences in color-excess.ipynb

- tutorials/Models-Quick-Fit/Models-Quick-Fit.ipynb
It looks like the Vizier column name for `__Ksmag__` changed...
> Change name of column and some whitespace fixes
