- check_env.py
- prepare_deploy.py
- tutorials/FITS-header/requirements.json
- tutorials/FITS-images/requirements.json
- tutorials/FITS-tables/requirements.json
- tutorials/Plot-Catalog/requirements.json
- tutorials/Quantities/requirements.json
- tutorials/UVES/requirements.json
Hey @taldcroft Regarding Issue 64 ...does this solution fix this?
I modified each check_env.py to check for packages that I thought were required , some packages might be extra or missing...Do tell me if you find something like this
Another potential issue is the oldest version of packages supported and the most compatible ones ( like in numpy is anything below 1.6.0 supported , if yes, till which version) maybe be absent or wrongly coded.
> Fixing Issue #64

- tutorials/Coordinates/Coordinates.ipynb
Just what the title says... Previously it only worked in py 2 (as pointed out by @astrofrog)
The diff is weirdly large, though ... the only content change is the change to the cell that import urllib (and where it's called)... I'm not sure why so much of the file changed.  Maybe a new nb format?
cc @astrofrog @adrn
> update coordinates tutorial to have a py 2/3 compliant use of urllib

- .travis.yml
- conda-environment.yml
- pip-requirements.txt
- tutorials/Coordinates/requirements.json
- tutorials/Coordinates/requirements.txt
- tutorials/FITS-header/requirements.json
- tutorials/FITS-header/requirements.txt
- tutorials/FITS-images/requirements.json
- tutorials/FITS-images/requirements.txt
- tutorials/FITS-tables/requirements.json
- tutorials/FITS-tables/requirements.txt
- tutorials/Plot-Catalog/requirements.json
- tutorials/Plot-Catalog/requirements.txt
- tutorials/Quantities/requirements.json
- tutorials/Quantities/requirements.txt
- tutorials/UVES/requirements.json
- tutorials/UVES/requirements.txt
- tutorials/redshift_plot/requirements.json
- tutorials/redshift_plot/requirements.txt
Added global pinned versions in pip requirements and conda environment file, added individual requirements.txt files for tutorials and removed out of date JSON versions
> Tidy up files specifying requirements

- tutorials/notebooks/vo/conesearch.ipynb
Fix #175 
c/c @adrn @eteq 
I don't know why Jupyter inserted some voodoo incantations. Please let me know if you want me to scrub them off with my good ol' Emacs.
> Cone Search example to handle situation of RA and DEC column names changing

- tutorials/notebooks/FITS-images/FITS-images.ipynb
- tutorials/notebooks/FITS-tables/FITS-tables.ipynb
- tutorials/notebooks/UVES/UVES.ipynb
- tutorials/notebooks/coordinates/coordinates.ipynb
- tutorials/notebooks/plot-catalog/plot-catalog.ipynb
- tutorials/notebooks/quantities/quantities.ipynb
- tutorials/notebooks/redshift-plot/redshift-plot.ipynb
- tutorials/notebooks/vo/conesearch.ipynb
> Remove custom astropy matplotlib style

- scripts/convert.py
- tutorials/_static/custom.css
- tutorials/conf.py
The resolution of the output plots isn't great for retina / hi-res screens. I think this will improve the output PNG resolution? I still need to test this, but opening the PR to keep track.
> Style changes

- CONTRIBUTING.rst
> Move some documentation between dev and contrib docs

- CONTRIBUTING.rst
- Makefile
- tutorials/_static/custom.css
- tutorials/astropy.tpl
Fixes #197 
This identifies any markdown cell that starts with "# Introduction" and re-styles it to have a blue background. The particular string "# Introduction" could be anything, or could even be in the cell metadata.
Also, the style I chose was just to show off that we can control it with CSS, so feel free to suggest other ideas!
> Better header

- tutorials/notebooks/FITS-header/FITS-header.ipynb
I have added another step to the FITS_header tutorial and a bit more explanation.
> updated FITS_header tutorial

- pip-requirements.txt
Big warning on the titlepage, this should fix it without messing up any other parts (newer versions are available, too).
> Update requirement to avoid security vulnerability

- tutorials/notebooks/Models-Quick-Fit/Models-Quick-Fit.ipynb
This just fixes a few markdown/RST issues in the new tutorial.
> Fix some link formatting issues in new Model fitting tutorial

- tutorials/notebooks/vo/conesearch.ipynb
The conesearch tutorial was failing for me, I *think* because of a change in the remote server?
This is a pretty minor change that just makes it a bit more robust, I think, at the cost of a bit of complexity.
cc @pllim @adrn
> update conesearch notebook to be a bit more robust

- tutorials/notebooks/Coordinates-Intro/Coordinates-Intro.ipynb
- tutorials/notebooks/Coordinates-Transform/Coordinates-Transform.ipynb
- tutorials/notebooks/FITS-cubes/FITS-cubes.ipynb
- tutorials/notebooks/FITS-header/FITS-header.ipynb
- tutorials/notebooks/FITS-images/FITS-images.ipynb
- tutorials/notebooks/FITS-tables/FITS-tables.ipynb
- tutorials/notebooks/Models-Quick-Fit/Models-Quick-Fit.ipynb
- tutorials/notebooks/UVES/UVES.ipynb
- tutorials/notebooks/plot-catalog/plot-catalog.ipynb
- tutorials/notebooks/quantities/quantities.ipynb
- tutorials/notebooks/redshift-plot/redshift-plot.ipynb
- tutorials/notebooks/synthetic-images/synthetic-images.ipynb
- tutorials/notebooks/units-and-integration/units-and-integration.ipynb
- tutorials/notebooks/vo/conesearch.ipynb
This PR is essentially just a bunch of grammatical edits to make the language in the tutorials a little more consistent. I also tried to fix any formatting issues along the way.
> Grammatical edits and consistency

- tutorials/notebooks/UVES/UVES.ipynb
> minor change to UVES tutorial header

- CONTRIBUTING.rst
Moved Jupyter notebook header template to earlier in the document.
Wrote a section for using Colaboratory to submit Jupyter notebooks
> Update Contributing documentation for Colaboratory workflow

- quarantine/FITS-cubes/FITS-cubes.ipynb
Fairly minor things, but it's quite a bit simpler this way
(also, you should pretty much never do `cube.hdu.data[...]`, there are always better ways, unless we've made a huge design mistake)
> Some cube tutorial fixes

- .rtd-environment.yml
- environment.yml
- pip-requirements.txt
Currently github complains of a security vulnerability in versions of the notebook < 5.7.2 .  This PR just updates the various places we give an nb version to address that.
cc @adrn
> update nb to 5.7.2

- tutorials/_static/astropy.css
- tutorials/themes/tutorials-theme/navbar.html
> Improved responsiveness

- tutorials/notebooks/FITS-tables/FITS-tables.ipynb
- tutorials/themes/tutorials-theme/navbar.html
> Fix navbar logo

- tutorials/notebooks/FITS-images/FITS-images.ipynb
From 'histrogram' to 'histogram'
> Fixed typo

- tutorials/_static/astropy.css
- tutorials/themes/tutorials-theme/tutorialfilters.html
> keyword categories added and view-more dropdown implemented

- tutorials/themes/tutorials-theme/navbar.html
To fix some broken links introduced after rebranding to "learn.astropy.org".
> Update ``href`` of both brand logo and banner in "navbar.html"

- environment.yml
- pip-requirements.txt
- tutorials/notebooks/color-excess/color-excess.ipynb
- tutorials/notebooks/color-excess/requirements.txt
- tutorials/notebooks/quantities/requirements.txt
After working on the notebook collaboratively with @krislars, this PR provides the changes to PR #240 with a clean commit history.
> Clean commit of color excess tutorial

- tutorials/astropy.tpl
> Fix links on bottom of tutorial page

- tutorials/themes/tutorials-theme/navbar.html
This is my attempt to fix #351
@astrofrog - can you check the rendered docs and see if this fixes the issue for you? It does on my browser.
> Add more margin to documentation card

- tutorials/notebooks/quantities/quantities.ipynb
I forgot to add myself as an author.
> add myself to the author list on Quantities tutorial

- tutorials/themes/tutorials-theme/tutorialfilters.html
modifications to website to update keyword list.
> Website keywords

- tutorials/notebooks/Coordinates-Intro/Coordinates-Intro.ipynb
- tutorials/notebooks/FITS-cubes/FITS-cubes.ipynb
- tutorials/notebooks/FITS-tables/FITS-tables.ipynb
- tutorials/notebooks/Models-Quick-Fit/Models-Quick-Fit.ipynb
- tutorials/notebooks/coordinates/coordinates.ipynb
- tutorials/notebooks/synthetic-images/synthetic-images.ipynb
- tutorials/notebooks/vo/conesearch.ipynb
- tutorials/notebooks/vo/requirements.txt
Keyword and polish to several tutorials.
> Keyword updates round 2.

- tutorials/notebooks/vo/conesearch.ipynb
Again! xref astropy/astroquery#1543
> vo_conesearch: Update vos_baseurl

- tutorials/themes/tutorials-theme/tutorialfilters.html
I have a setTimeout delay of 1 sec after on load of the tutorials page to display the correct number of tutorials.
Fixes #397
> Added a setTimeout after on load of tutorials page

- tutorials/notebooks/color-excess/color-excess.ipynb
> color-excess tutorial: Install synphot with pip

- .circleci/config.yml
- tutorials/notebooks/quantities/quantities.ipynb
- tutorials/notebooks/quantities/requirements.txt
Fixes #447. 
Update tutorial content to pass CI checks.
> Update Quantities notebook

- .circleci/config.yml
- pip-requirements.txt
This is a temporary fix for the failing FITS-cubes tutorial - see #463 and https://github.com/astropy/astroquery/issues/1856
> Install the dev version of astroquery

- tutorials/notebooks/FITS-cubes/FITS-cubes.ipynb
Similar to astropy/astropy#11111
cc @mwcraig
> DOC: Replace astropy channel with conda-forge

- tutorials/notebooks/color-excess/color-excess.ipynb
Changed astroquery.mast observation id
EDIT: Fix #481
> Fix bug in color-excess.ipynb

- .github/get_modified_tutorials.py
- .github/workflows/prs.yml
- Makefile
This adds a new Makefile with commands to help with running the nbcollection build, and a command to check the user's python environment to make sure it contains all of the required dependencies.
Closes #64
> Add Makefile to simplify local and CI builds

- .github/get_modified_tutorials.py
- .github/workflows/prs.yml
- .github/workflows/test-scripts.yml
> Enable get_modified_tutorials.py script to find staged and unstaged (i.e. uncommitted) changed files

- Makefile
This is an alternate to #507 using the new Makefile build!
> Enabled ExtractOutputPreprocessor

- .github/PULL_REQUEST_TEMPLATE.md
This adds a short checklist that asks contributors to check the contributing guide or acknowledge they are aware of the procedure, and asks for acknowledging the code of conduct. 
Thoughts for other things to include here?
> Add a pull request template 

- requirements.txt
> Experimental pin of pyvo version

- tutorials/User-Defined-Model/User-Defined-Model.ipynb
- [ x] Check the box to confirm that you are familiar with the [contributing guidelines](https://learn.astropy.org/contributing/how-to-contribute) and/or indicate (check the box) that you are familiar with our contributing workflow.
- [x ] Confirm that any contributed tutorials contain a complete Introduction which includes an Author list, Learning Goals, Keywords, Companion Content (if applicable), and a Summary.
- [x ] Check the box to confirm that you are familiar with the Astropy community [code of conduct](https://github.com/astropy/astropy/blob/main/CODE_OF_CONDUCT.md) and you agree to follow the CoC.
> Fixed error in derivative in Full custom model section

- tutorials/astropy-coordinates/2-Coordinates-Transforms.ipynb
- tutorials/astropy-coordinates/requirements.txt
> Update to Coordinate Tutorial 2

- .github/workflows/build.yml
- .github/workflows/prs.yml
This is just to deal with some out of date GitHub actions workflows. The build will probably still fail but @jeffjennings and I are working on getting the tutorials build going again!
> Update versions like a human dependabot

- tutorials/color-excess/color-excess.ipynb
Implements suggestion in #433. Closes #433.
> color-excess: update synphot call
